name: Deploy to AWS using OIDC

on:
  push:
    branches: main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::439712476071:role/neuron-git-role
          aws-region: us-west-2

      - name: Deploy to S3
        run: aws s3 sync ./build s3://www.neuronprocess.com --delete
